import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Main } from './main';

const roboto = Roboto({
    weight: ['100', '300', '400', '700', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    appleWebApp: true,
    themeColor: '#e4e4e7',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="de">
            <body className={roboto.className}>
                <Main>{children}</Main>
            </body>
        </html>
    );
}
